version: '3.4'
services:
  php:
    image: n0dwis/php:0.1
    build: ./php
    networks:
        - main
    volumes:
        - "code:/var/www/uts24.ru"

  nginx:
    image: n0dwis/nginx:0.1
    build: ./nginx
    volumes:
      - "code:/var/www/uts24.ru"
    networks:
      - main
    ports:
      - 80:80

  postgres:
    image: n0dwis/postgres:0.1
    build: ./postgres
    hostname: 'postgres'
    networks:
      - main
    ports:
      - 5432:5432
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - "/home/postgresql/9.5/main:/data"

  mongo:
    image: 'mongo:4.0.0'
    hostname: 'mongo'
    networks:
      - main

networks:
  main:

volumes:
  code:
    driver_opts:
      type: none
      device: /home/www/uts24.ru
      o: bind
