version: '3.4'
services:
  php:
    build: ./php
    networks:
        - main
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    networks:
        - main
  postgres:
    build: ./postgres
    networks:
        - main


networks:
  main:
