#!/bin/zsh
#Some shell functions to simplify working

ds () {
    docker-compose exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" "$1" /bin/sh
}

dup () {
    if [ "$1" != "" ]; then
        CONTAINER="$1"
    else
        CONTAINER=
    fi;
    docker-compose up -d --build ${CONTAINER}
}

ddown () {
    if [ "$1" != "" ]; then
        CONTAINER="$1"
    else
        CONTAINER=
    fi;
    docker-compose down ${CONTAINER}
}

dstart () {
    if [ "$1" != "" ]; then
        CONTAINER="$1"
    else
        CONTAINER=
    fi;
    docker-compose start ${CONTAINER}
}

dstop () {
    if [ "$1" != "" ]; then
        CONTAINER="$1"
    else
        CONTAINER=
    fi;
    docker-compose stop ${CONTAINER}
}

dlog () {
    docker-compose logs $1
}


alias dps='docker ps --format="table {{.ID}}\t{{.Names}}\t{{.Status}}"'
