#!/bin/sh

mkdir -p /home/www-data/.ssh
cp $SSH_KEY /home/www-data/.ssh/id_rsa
chown www-data:www-data -R /home/www-data/.ssh

if [ -n "$HOST_GROUP_ID" ]; then
    GROUP = "$(cat /etc/group | grep $HOST_GROUP_ID | cut -d ':' -f 1)"

fi

docker-php-entrypoint "$@"
